#!/usr/bin/env bash
#
# Manual verification of the Seatbelt sandbox profile (ADR-0011).
#
# CI runners are linux where sandbox-exec does not exist, so the real
# four-state behaviour (workspace writable / workspace rm allowed / deny
# island protected / outside denied unless config-allowed) is verified here
# against the profile generator from the built dist. Run on macOS after
# `pnpm build`:
#
#   bash scripts/verify-sandbox.sh
#
set -euo pipefail

command -v sandbox-exec >/dev/null || { echo "SKIP: sandbox-exec not available (non-macOS?)"; exit 0; }
[ -f dist/backend/sandbox.js ] || { echo "FAIL: dist not built — run pnpm build first"; exit 1; }

# Fixtures live under /tmp, NOT $TMPDIR — the profile allowlists TMPDIR, so
# fixtures there would be swallowed by that rule and prove nothing. /tmp is
# symlinked to /private/tmp on macOS; the generator realpaths it.
WS=$(mktemp -d /tmp/sbv-ws-XXXXXX)/project && mkdir -p "$WS/.zcode/acp"
OUTSIDE=$(mktemp -d /tmp/sbv-out-XXXXXX)
DENIED=$(mktemp -d /tmp/sbv-denied-XXXXXX)
ISLAND="$WS/.zcode/acp"
echo "decoy" > "$DENIED/decoy.txt"

# Project config opting this workspace in and granting OUTSIDE — the file the
# bridge auto-creates (enabled:false) and the user flips, and which the deny
# island keeps the agent from editing. DENIED stays out of the config.
printf '{\n  "enabled": true,\n  "allow": ["%s"],\n  "strictGit": false\n}\n' "$OUTSIDE" > "$ISLAND/sandbox.json"

# Arm via the REAL production path: no env, project config enabled:true, and
# the profile generated by armSandboxArgv itself (fresh O_EXCL dir + self-deny)
# — the checks below run against exactly what the backend would run under.
unset ZCODE_ACP_SANDBOX
PROFILE=$(node --input-type=module - "$WS" <<'EOF'
import { readFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { armSandboxArgv, sandboxActive } from "./dist/backend/sandbox.js";
const [ws] = process.argv.slice(2);
if (sandboxActive([ws]) !== true) {
  console.error("FAIL: enabled:true did not arm the sandbox without the env");
  process.exit(1);
}
const config = JSON.parse(readFileSync(`${ws}/.zcode/acp/sandbox.json`, "utf8"));
const argv = armSandboxArgv(["/bin/true"], {
  workspaces: [{ root: ws, config }],
  extraAllow: [],
});
// Invariant: the profile must live outside every whitelisted path (home
// base) — $TMPDIR placement was raced across sandbox generations in review.
const profilePath = argv[2];
if (!profilePath.startsWith(path.join(os.homedir(), ".zcode-acp-sbx-"))) {
  console.error(`FAIL: profile outside home base: ${profilePath}`);
  process.exit(1);
}
console.log(profilePath);
EOF
) || exit 1
echo "PASS: project config enabled:true arms (no env); profile: $PROFILE"

fail=0
check() { # name, command, expected-exit
  local name=$1 cmd=$2 want=$3 got
  if eval "$cmd" >/dev/null 2>&1; then got=0; else got=$?; fi
  if [ "$got" = "$want" ]; then echo "PASS: $name"; else echo "FAIL: $name (exit=$got want=$want)"; fail=1; fi
}

SANDBOX="sandbox-exec -f $PROFILE"
check "workspace write allowed"    "$SANDBOX touch $WS/ok.txt" 0
check "workspace rm allowed"       "$SANDBOX rm $WS/ok.txt" 0
check "outside write denied"       "$SANDBOX touch $DENIED/nope.txt" 1
check "outside rm denied"          "$SANDBOX rm $DENIED/decoy.txt" 1
check "deny island write denied"   "$SANDBOX touch $ISLAND/nope.json" 1
check "config allow honored"       "$SANDBOX touch $OUTSIDE/yes.txt" 0
# /dev/null: git and shell redirect idioms break without this allow.
check "/dev/null writable"         "$SANDBOX sh -c 'echo x > /dev/null'" 0
# The profile self-denies its own dir: a sandboxed process must not be able
# to race/symlink/occupy the next respawn's profile.
check "profile self-denied"        "$SANDBOX sh -c 'echo evil > $PROFILE'" 1

rm -rf "$(dirname "$WS")" "$OUTSIDE" "$DENIED" "$(dirname "$PROFILE")"
if [ "$fail" = 0 ]; then echo "ALL PASS"; else exit 1; fi
